books/urls.py
from django.urls import path , include
from books.views import showallbooks,deletebooks,editbooks,upload_file,borrow_book



urlpatterns=[
    path('add',upload_file,name='addbook'),
    path('showallbooks',showallbooks,name="showallbooks"),
    path('deletebooks/<int:id>',deletebooks , name="deletebooks"),
    path('editbooks/<int:id>',editbooks,name="editbooks"),
    path('',upload_file,name='upload'),
    path('book/<uuid:pk>/borrow/', borrow_book, name='borrow_book'),

]

home/urls.py
from django.urls import path , include

from home.views import home ,bookdetails,contact,regform,profilestudent,showstudentdetails,signin,search

urlpatterns=[

path('',home,name='home'),
path("book/<int:id>",bookdetails,name='bookdetails'),
path('contact',contact,name='contact'),
path('signup',regform,name="signup"),
path('student/<int:id>',profilestudent ,name="profilestudent"),
path('studentdetails',showstudentdetails,name="studentdetails"),
path('signin',signin ,name="signin"),
path('searchstudent/',search ,name='search')
 

]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/',include('home.urls')),
    path('books/',include('books.urls')),
    path('admin/', admin.site.urls),
]

books/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
import uuid
# Create your models here.
class createbook(models.Model):
    name=models.CharField(max_length=50) 
    img=models.CharField(max_length=200)
    descriptione=models.CharField(max_length=200)
    docfile =models.CharField(max_length=100)


    def __str__(self):
        return self.name
   
class student(models.Model):
    name=models.CharField(max_length=50)
    age=models.IntegerField()
    email=models.EmailField(max_length=100)
    img=models.CharField(max_length=200)
    password=models.CharField(max_length=50)
    phone=models.CharField(max_length=20)
    address=models.CharField(max_length=30)
    
    def __str__(self):
        return self.name
    


class BookInstance(models.Model):
      id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
      book = models.ForeignKey('createbook', on_delete=models.SET_NULL, null=True)
      due_back = models.DateField(null=True, blank=True)
    
      STATUS_MAINTENANCE = 'm'
      STATUS_ON_LOAN = 'o'
      STATUS_AVAILABLE = 'a'
      STATUS_RESERVED = 'r'

      LOAN_STATUS = (
    (STATUS_MAINTENANCE, 'Maintenance'),
    (STATUS_ON_LOAN, 'On loan'),
    (STATUS_AVAILABLE, 'Available'),
    (STATUS_RESERVED, 'Reserved'),
    )

      status = models.CharField(
     max_length=1,
     choices=LOAN_STATUS,
     blank=True,
     default='m',
     help_text='Book availability',
  ) 

books/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from django.http import HttpResponse
from home.models import createbook ,BookInstance
from home.forms import books
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.


def addbook(request):
  print(request)
  print(request.method)
  if request.method == 'GET': 
    return render(request,'books/addbook.html')
  elif request.method =='POST':
    print(request.POST['name'])
    book=createbook()
    book.name=request.POST['name']
    book.img=request.File['img']
    book.descriptione=request.POST['desc']
    book.docfile=request.POST['file']
    book.save()
    return redirect('home')
   
    


def showallbooks(request):
  books=createbook.objects.all()    
  context = {"book":books}
  return render(request,'books/showbooks.html' ,context)


def deletebooks(request,id):
  book=get_object_or_404(createbook,pk=id)
  book.delete()
  return redirect('showallbooks')

def editbooks(request,id):
  book=get_object_or_404(createbook,pk=id)
  if request.method =="GET":
     context={'books':book}
     return render(request,'books/editbook.html',context)
  elif request.method =="POST":
    book.name=request.POST['name']
    book.img=request.POST['img']
    book.descriptione=request.POST['desc']
    book.save()
    return redirect('showallbooks')



def upload_file(request):
    if request.method == 'POST':
        form = books(request.POST, request.FILES)
        if form.is_valid():
            # file is saved
            form.save()
            return books('/success/url/')
    else:
        form = books()
    return render(request, 'books/addbook.html', {'form': form})



def borrow_book(request, pk):
   book_instance = get_object_or_404(BookInstance, pk=pk)
   if request.method == 'POST':
        if request.user.is_authenticated:
            book_instance.borrower = request.user
            book_instance.due_back = datetime.date.today() + datetime.timedelta(weeks=3)
            book_instance.status = 'STATUS_ON_LOAN'
            book_instance.save()
            return HttpResponseRedirect(reverse('dashboard_customer'))

   context = {
       'book_instance': book_instance,
    }

   return render(request, 'home/book_detail.html', context)

books/templates/books/addbook.html
{% extends '../home/layouts/base.html'%}
{% load static %}
{%block body%}

<form role="form"  method="post" action="" enctype="multipart/form-data">
    {% csrf_token%}
    <div class="card-body">
      <div class="form-group">
        <label> Name </label>
        <input type="text" class="form-control" name="name" placeholder="Enter the book name">
      </div>
      <br>
      <div class="form-group">
        <label> description</label>
        <input type="text" class="form-control" name="desc" placeholder="describe the book">
      </div>
      <br>
      <div class="form-group">
        <div class="custom-file">
          <input type="file" class="custom-file-input" name="file" id="exampleInputFile">
          <label class="custom-file-label" for="exampleInputFile">Choose file</label>
        </div>
      </div>
      <input type="file" name="myfile">
    
<br>

      
    </div>
    <!-- /.card-body -->
    <br>
    <div class="d-grid gap-2" >
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
  {% if uploaded_file_url %}
<p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
{% endif %}
{%endblock%}

books/templates/books/borrow.html
{% extends 'home/layouts/base.html'%}
{% load static %}
{%block body%}

      
            <div class="news">
                <div class="container-fluid">
                    <div class="row align-items-center">
                    
                        <div class="col-md-6">
                            {% for copy in book.bookinstance_set.all %}
                              {% if copy.status == 'a' %}

                          <form method="POST" action ="{% url 'borrow_book' copy.id%}" enctype="multipart/form-data">

                            {% csrf_token %}
                           <button type="submit" class="btn btn-success">Borrow the book</button>

                              </form>
                              {% endif %}
                                 {% endfor %} 
                   
                           
                       
                
                       </div>
                </div>
              </div>
            </div>
         
{%endblock%}

books/templates/books/editbook.html
{% extends '../home/layouts/base.html'%}
{% load static %}
{%block body%}

<form role="form"  method="post" action="">
    {% csrf_token%}
    <div class="card-body">
      <div class="form-group">
        <label> Name </label>
        <input type="text" class="form-control" name="name" value="{{books.name}}" placeholder="Enter the book name">
      </div>
      <br>
      <div class="form-group">
        <label> description</label>
        <input type="text" class="form-control" name="desc" value="{{books.descriptione}}" placeholder="describe the book">
      </div>
      <br>
      <div class="form-group">
     
        <label> Image</label>
        <input type="text" class="form-control" name="img" value="{{books.img}}" placeholder="Image">
    </div>
    <!-- /.card-body -->
    <br>
    <div class="d-grid gap-2" >
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>

{%endblock%}

books/templates/books/showbooks.html
{% extends '../home/layouts/base.html'%}
{% load static %}
{%block body%}

<table class="table">
  <thead>
    <tr>
      <th scope="col">Book Name</th>
      <th scope="col">Book Description</th>
      <th scope="col">Book Image</th>
      <th scope="col">Delete</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
   {% for i in book %}
   <div>
    <tr>
      <td>{{i.name}} </td>
      <td>{{i.descriptione}}</td>
      <td>{{i.img}}</td>
    <td>
        <div>
        <form action="{% url 'deletebooks' i.id %}" method="delete">
          {% csrf_token %}
         <input type="submit" class="btn btn-danger" value="Delete">
        </form> 
        </div>
      
        </td>

      <td>
        
          <a href="{% url 'editbooks' i.id %}"> <input type="submit" class="btn btn-primary" value="Edit"></a> 
           
      </td>
    </tr>
    </div>
{% endfor%}
  </tbody>
</table>

{%endblock%}